### ISSUE TITLE
more suggested changes to class

### ISSUE THREAD

**Issue by proseLA** [lat9/upsxml#36]
i am having the darndest time with this module.  

lets start here:

https://github.com/lat9/upsxml/blob/c16570e87e9058e304678e2783409beca161126b/includes/modules/shipping/upsxml.php#L37

i think the class should extend base.  that way we can add notifiers.

and the first notifier would go above here:

https://github.com/lat9/upsxml/blob/c16570e87e9058e304678e2783409beca161126b/includes/modules/shipping/upsxml.php#L427

UPS and all of the shipping companies are notorious for giving clients numerous account numbers for whatever reason....  i am currently creating a new class called `upsxml2` which extends `upsxml`; it has been the darndest (there's that word again) making it work.  i think i finally have it going.  all without changing base code!  except for in here...

very tricky.

and i am currently running live transactions with this section of code running:

```
//pRose fix for negotiated rates not coming back if state is not provided.
        $result = $this->_parseResult($xmlResult);
        if (is_string($result) && !empty($this->upsShipperNumber)) {
            $this->upsShipperNumber = '';
            return $this->_upsGetQuote();
        }
        return $result;
```

**Comment by lat9** [comment]
> and the first notifier would go above here:
> 
> https://github.com/lat9/upsxml/blob/c16570e87e9058e304678e2783409beca161126b/includes/modules/shipping/upsxml.php#L427
> 

I'm unclear as to what notification values should be included and what its response would override; please advise.

**Comment by proseLA** [comment]
i will provide the answer here, and then request that it gets added to the new upsoauth module (i can be very difficult).  

i have a client who gets different discounts based on the weight of the package.  UPS in their `infinite wisdom` decided that they need 2 different account numbers.  hence i have a copy of this module that extends this module.  

if we had an observer in this location, i would only quote each module based on the weight of the package.  something like:

```
        // pRose - only quote 1 service based on weight limit
        // upsxml2 is the lighter weight one, so anything less than the weightLimit
        // use 0 for everything to go with upsxml
        if ($shipping_weight < $this->weightLimit) {
            if ($this->code === 'upsxml') {
                return;
            }
        } elseif ($this->code === 'upsxml2') {
            return;
        }
```
and now it makes sense to me!

the observer would be there to determine whether or not to quote the service, ie return from the method.
